name: CI

on:
  pull_request:
    branches:
      - master

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: oven-sh/setup-bun@v2

      - uses: taiki-e/install-action@bfadeaba214680fb4ab63e710bcb2a6a17019fdc # v2.70.4
        with:
          tool: just

      - run: bun i --frozen-lockfile

      - name: Format check
        run: just format-check

      - name: Lint
        run: just lint

      - name: Typecheck
        run: just typecheck

      - name: Test
        run: just test
